apiVersion: v1
kind: Service
metadata:
  name: mysql-h # este nome tem que bater com o nome contido na aplicacao do statufulset
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None # obrigatoriamente eh none
