apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-h
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: mysql
  replicas: 4
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts: # faz o vinculo do volume com o pod
            - mountPath: /var/lib/mysql
              name: mysql-volume 

  volumeClaimTemplates: # cria o template; a cada pod novo, um volume novo sera criado
    - metadata:
        name: mysql-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi